#####Intro to Pandas
***
Following [this](http://pandas.pydata.org/pandas-docs/stable/10min.html) tutorial.

In [20]:
# Imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Convenience imports
from IPython.display import display # display(your_stuff)

#####Object Creation
***

In [21]:
# Create a Series
s = pd.Series([1, 3, 5, np.nan, 6, 8])
s

0     1
1     3
2     5
3   NaN
4     6
5     8
dtype: float64

In [28]:
# Create a DataFrame

# create dates separated into periods - which are just days
dates = pd.date_range('20130101', periods=6)
display(dates)

# create an arary: np.random.randn(6, 4) -> array(y, x) of random numbers
display(np.random.randn(6, 4))

# pd.DataFrame(row_values, index=row_names, columns=column_names)
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list('ABCD'))
display(df)

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D', tz=None)

array([[ 1.01461626,  0.90713026, -1.31882102, -1.28262518],
       [-0.29282161, -0.60469734,  0.29277958,  1.83001052],
       [-0.96803134, -2.51369681, -1.48004624,  0.23880916],
       [-0.94046969, -0.43920537,  1.23091556, -0.34015811],
       [ 1.2542869 ,  0.30401143,  1.11417919,  1.51802581],
       [-1.79681368, -0.8144957 , -2.932213  , -0.04210498]])

A         B         C         D
2013-01-01  1.643279 -0.053740  0.041391  0.632955
2013-01-02 -0.352140 -1.244643 -0.258014  0.588093
2013-01-03 -0.319649 -1.092092 -1.076724 -0.462859
2013-01-04  0.324585  1.308598  0.026085 -0.950834
2013-01-05  1.412181  0.411211  1.487764  1.005027
2013-01-06 -1.779313  0.501028  0.177729 -0.265334

In [44]:
# create dataframe from a dictionary - {col_name: values}
#     >> np.array([[1, 2], [3, 4]], dtype="int32"): 
#        array([[3, 3, 3, 3],
#               [3, 3, 3, 3]], dtype=int32)
df2 = pd.DataFrame({ 'A' : 1.,
                     'B' : pd.Timestamp('20130102'),
                     'C' : pd.Series(1,index=list(range(4)),dtype='float32'),
                     'D' : np.array([3] * 4,dtype='int32'),
                     'E' : pd.Categorical(["test","train","test","train"]),
                     'F' : 'foo' })

print ("Dictionary representation:")
display(df2.to_dict())

print ("Data frame representation:")
display(df2)

print ("Check all data types:")
display(df2.dtypes)

Dictionary representation:


{'A': {0: 1.0, 1: 1.0, 2: 1.0, 3: 1.0},
 'B': {0: Timestamp('2013-01-02 00:00:00'),
  1: Timestamp('2013-01-02 00:00:00'),
  2: Timestamp('2013-01-02 00:00:00'),
  3: Timestamp('2013-01-02 00:00:00')},
 'C': {0: 1.0, 1: 1.0, 2: 1.0, 3: 1.0},
 'D': {0: 3, 1: 3, 2: 3, 3: 3},
 'E': {0: 'test', 1: 'train', 2: 'test', 3: 'train'},
 'F': {0: 'foo', 1: 'foo', 2: 'foo', 3: 'foo'}}

Data frame representation:


A          B  C  D      E    F
0  1 2013-01-02  1  3   test  foo
1  1 2013-01-02  1  3  train  foo
2  1 2013-01-02  1  3   test  foo
3  1 2013-01-02  1  3  train  foo

Check all data types:


A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object

#####Viewing Data
***

In [52]:
# see the top & bottom rows of the frame
print "Display all data frame:"
display(df)

print "Display top 2 rows:"
display(df.head(2))

print "Display bottom 3 rows:"
display(df.tail(3))

Display all data frame:


A         B         C         D
2013-01-01  1.643279 -0.053740  0.041391  0.632955
2013-01-02 -0.352140 -1.244643 -0.258014  0.588093
2013-01-03 -0.319649 -1.092092 -1.076724 -0.462859
2013-01-04  0.324585  1.308598  0.026085 -0.950834
2013-01-05  1.412181  0.411211  1.487764  1.005027
2013-01-06 -1.779313  0.501028  0.177729 -0.265334

Display top 2 rows:


A         B         C         D
2013-01-01  1.643279 -0.053740  0.041391  0.632955
2013-01-02 -0.352140 -1.244643 -0.258014  0.588093

Display bottom 3 rows:


A         B         C         D
2013-01-04  0.324585  1.308598  0.026085 -0.950834
2013-01-05  1.412181  0.411211  1.487764  1.005027
2013-01-06 -1.779313  0.501028  0.177729 -0.265334

In [66]:
# display index (row_names), columns, and underlying numpy data
display(df.index)

display(df.columns)

display(df.values) 

display(df.describe())

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D', tz=None)

Index([u'A', u'B', u'C', u'D'], dtype='object')

array([[ 1.6432787 , -0.05373985,  0.0413913 ,  0.63295476],
       [-0.35213996, -1.2446432 , -0.25801363,  0.58809293],
       [-0.31964911, -1.092092  , -1.0767237 , -0.46285857],
       [ 0.32458502,  1.30859832,  0.02608493, -0.95083353],
       [ 1.41218055,  0.41121062,  1.48776372,  1.00502672],
       [-1.77931259,  0.50102838,  0.17772897, -0.26533397]])

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.154824 -0.028273  0.066372  0.091175
std    1.268722  0.987162  0.830289  0.760975
min   -1.779313 -1.244643 -1.076724 -0.950834
25%   -0.344017 -0.832504 -0.186989 -0.413477
50%    0.002468  0.178735  0.033738  0.161379
75%    1.140282  0.478574  0.143645  0.621739
max    1.643279  1.308598  1.487764  1.005027

In [72]:
# take actions on the data
print "Transpose (pivot) the data: "
display(df.T)

print "Sort the data: "
display(df)
display(df.sort_index(axis=1, ascending=False))

Transpose (pivot) the data: 


2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06
A    1.643279   -0.352140   -0.319649    0.324585    1.412181   -1.779313
B   -0.053740   -1.244643   -1.092092    1.308598    0.411211    0.501028
C    0.041391   -0.258014   -1.076724    0.026085    1.487764    0.177729
D    0.632955    0.588093   -0.462859   -0.950834    1.005027   -0.265334

Sort the data: 


A         B         C         D
2013-01-01  1.643279 -0.053740  0.041391  0.632955
2013-01-02 -0.352140 -1.244643 -0.258014  0.588093
2013-01-03 -0.319649 -1.092092 -1.076724 -0.462859
2013-01-04  0.324585  1.308598  0.026085 -0.950834
2013-01-05  1.412181  0.411211  1.487764  1.005027
2013-01-06 -1.779313  0.501028  0.177729 -0.265334

D         C         B         A
2013-01-01  0.632955  0.041391 -0.053740  1.643279
2013-01-02  0.588093 -0.258014 -1.244643 -0.352140
2013-01-03 -0.462859 -1.076724 -1.092092 -0.319649
2013-01-04 -0.950834  0.026085  1.308598  0.324585
2013-01-05  1.005027  1.487764  0.411211  1.412181
2013-01-06 -0.265334  0.177729  0.501028 -1.779313

In [114]:
"""
    - Open a file with columns and rows
    - clean rows with particular values
    - reindex the data frame
    - add missing data for missing indexes
    - convert columns to list/dict
"""
import pandas as pd
import csv

data_file = open('/Users/whitehat/Desktop/facs_standard.txt', 'r')
file_name = os.path.basename(data_file.name).split('.')[0]

sniffer = csv.Sniffer()
dialect = sniffer.sniff(data_file.read().replace('\r', '\n'))
print dialect.delimiter
# returns ','

data_file.seek(0)
df = pd.read_csv(data_file, sep=dialect.delimiter)
antigens = df.columns[1:]
current_indexes = [int(line.split(":")[0]) for line in df['Sample'] if line not in ('Mean', 'StdDev')]
full_index = range(1, 97)

# ~df['column_name'].isin(some_values) == # df = df[df.Sample != 'Mean'] and df = df[df.Sample != 'StdDev']
df = df.loc[~df['Sample'].isin(['Mean', 'StdDev'])]
df.index += 1
df.index = current_indexes
df = df.reindex(full_index, fill_value=1)
result = {"{} - {}".format(file_name, antigen): list(df[antigen])  for antigen in antigens}
df

Sample  CHOk1  CHO HuPTHR  CHO MSPTHR
1     1: Specimen_001_A1_A01.fcs   5.69       13.70       14.20
2     2: Specimen_001_A2_A02.fcs   5.21       12.40       26.70
3     3: Specimen_001_A3_A03.fcs   7.52     2988.00     7844.00
4     4: Specimen_001_A4_A04.fcs   6.20       11.90       20.30
5     5: Specimen_001_A5_A05.fcs   7.01        8.61       12.70
6     6: Specimen_001_A6_A06.fcs   6.24        9.19       11.00
7     7: Specimen_001_A7_A07.fcs  10.30      422.00      647.00
8     8: Specimen_001_A8_A08.fcs   7.47     1006.00     2087.00
9     9: Specimen_001_A9_A09.fcs   9.72     1314.00     2537.00
10  10: Specimen_001_A10_A10.fcs   6.83     3403.00     8035.00
11  11: Specimen_001_A11_A11.fcs   6.51      528.00       10.10
12  12: Specimen_001_A12_A12.fcs   9.23     1238.00      105.00
13   13: Specimen_001_B1_B01.fcs   6.32      178.00      124.00
14   14: Specimen_001_B2_B02.fcs   7.22      115.00       87.10
15   15: Specimen_001_B3_B03.fcs  10.10     3849.00       27.90
16   16: Specimen_001_B4_B04.fcs   7.46     3180.00       10.80
17   17: Specimen_001_B5_B05.fcs   5.99        8.33        8.02
18   18: Specimen_001_B6_B06.fcs   6.98        8.54       10.00
19   19: Specimen_001_B7_B07.fcs   1.00        1.00        1.00
20   20: Specimen_001_B8_B08.fcs   1.00        1.00        1.00
21   21: Specimen_001_B9_B09.fcs   1.00        1.00        1.00
22  22: Specimen_001_B10_B10.fcs   1.00        1.00        1.00
23  23: Specimen_001_B11_B11.fcs   1.00        1.00        1.00
24  24: Specimen_001_B12_B12.fcs   1.00        1.00        1.00
25   25: Specimen_001_C1_C01.fcs   1.00        1.00        1.00
26   26: Specimen_001_C2_C02.fcs   1.00        1.00        1.00
27   27: Specimen_001_C3_C03.fcs   1.00        1.00        1.00
28   28: Specimen_001_C4_C04.fcs   1.00        1.00        1.00
29   29: Specimen_001_C5_C05.fcs   1.00        1.00        1.00
30   30: Specimen_001_C6_C06.fcs   1.00        1.00        1.00
..                           ...    ...         ...         ...
67   67: Specimen_001_F7_F07.fcs   1.00        1.00        1.00
68   68: Specimen_001_F8_F08.fcs   1.00        1.00        1.00
69   69: Specimen_001_F9_F09.fcs   1.00        1.00        1.00
70  70: Specimen_001_F10_F10.fcs   1.00        1.00        1.00
71  71: Specimen_001_F11_F11.fcs   1.00        1.00        1.00
72  72: Specimen_001_F12_F12.fcs   1.00        1.00        1.00
73   73: Specimen_001_G1_G01.fcs   1.00        1.00        1.00
74   74: Specimen_001_G2_G02.fcs   1.00        1.00        1.00
75   75: Specimen_001_G3_G03.fcs   1.00        1.00        1.00
76   76: Specimen_001_G4_G04.fcs   1.00        1.00        1.00
77   77: Specimen_001_G5_G05.fcs   1.00        1.00        1.00
78   78: Specimen_001_G6_G06.fcs   1.00        1.00        1.00
79   79: Specimen_001_G7_G07.fcs   1.00        1.00        1.00
80   80: Specimen_001_G8_G08.fcs   1.00        1.00        1.00
81   81: Specimen_001_G9_G09.fcs   1.00        1.00        1.00
82  82: Specimen_001_G10_G10.fcs   1.00        1.00        1.00
83  83: Specimen_001_G11_G11.fcs   1.00        1.00        1.00
84  84: Specimen_001_G12_G12.fcs   1.00        1.00        1.00
85   85: Specimen_001_H1_H01.fcs   1.00        1.00        1.00
86   86: Specimen_001_H2_H02.fcs   1.00        1.00        1.00
87   87: Specimen_001_H3_H03.fcs   1.00        1.00        1.00
88   88: Specimen_001_H4_H04.fcs   1.00        1.00        1.00
89   89: Specimen_001_H5_H05.fcs   1.00        1.00        1.00
90   90: Specimen_001_H6_H06.fcs   1.00        1.00        1.00
91   91: Specimen_001_H7_H07.fcs   1.00        1.00        1.00
92   92: Specimen_001_H8_H08.fcs   1.00        1.00        1.00
93   93: Specimen_001_H9_H09.fcs   1.00        1.00        1.00
94                             1   1.00        1.00        1.00
95                             1   1.00        1.00        1.00
96  96: Specimen_001_H12_H12.fcs   4.56     1262.00     3338.00

[96 rows x 4 columns]